// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "Gas Junction Cannabis",
  domain: "gasjunctioncannabis.com",
  city: "Toronto",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-toronto",
  address: "2813 Dundas St W, Toronto, ON M6P 1Y6",
  streetAddress: "2813 Dundas St W",
  postalCode: "M6P 1Y6",
  phone: "(437) 535-7027",
  phoneIntl: "+14375357027",
  neighborhood: "The Junction",
  nearbyAreas: ["The Junction", "Dundas St W", "Keele", "High Park North", "Junction Triangle", "Bloor West Village", "Runnymede", "Annette Street", "Dundas West", "Roncesvalles"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "",
  mapEmbedUrl: "",
  latitude: "43.6651700",
  longitude: "-79.4630600",
  hours: ["Open Daily: 09:00 AM - 02:00 AM"],
  seoTitle: "Gas Junction Cannabis | Weed Dispensary in Toronto",
  metaDescription: "Gas Junction Cannabis is a local weed dispensary in Toronto with flower, pre-roll, edible, vape, concentrate, accessory, and cigarette category information for adults 19+.",
  localLandmarks: ["The Junction", "Dundas St W", "Keele"],
  introVariant: "Gas Junction Cannabis is listed at 2813 Dundas St W in Toronto. Adults 19+ can use this page to review store details, menu categories, hours, and contact information before visiting The Junction location.",
  neighborhoodDescription: "Gas Junction Cannabis is located in The Junction area of Toronto near Dundas St W and Keele.",
  parkingNote: "Street parking and nearby parking options may be available around Dundas St W. Please check posted signs when visiting.",
  transitNote: "Gas Junction Cannabis is accessible by local TTC routes serving Dundas St W, Keele, and Toronto’s Junction area.",
  sectionTitle: "Serving Customers Near The Junction and Dundas St W"
};
